# Site
repository: daanverraes/daanverraes.github.io/tree/main
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Daan Verraes
title: PhD Researcher | Engineer | Innovator
email: daan.verraes@ugent.be
website: https://daanverraes.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: daanverraes
linkedin_username: daanverraes
instagram_username: daanverraes
orcid_username: 0009-0001-7403-628X

# Additional icon links
additional_links:
  - title: MolMod Group Profile
    icon: fas fa-atom
    url: https://molmod.ugent.be/members/daan-verraes

# Google Analytics and Tag Manager
google_analytics: "UA-12345678-9"

# Hero Section
hero:
  title: "Hi, I'm Daan Verraes"
  subtitle: "PhD Researcher at Ghent University"
  profile_image: images/pf_blanco.jpg
  description: |
    Passionate about theoretical and computational quantum mechanics. 
    Exploring the intersection of physics, mathematics, and computing.
  cta_buttons:
    - text: "Contact Me"
      link: mailto:daan.verraes@ugent.be
      icon: fas fa-envelope
    - text: "View My Research"
      link: https://molmod.ugent.be/members/daan-verraes
      icon: fas fa-external-link-alt

# About Section
about:
  title: About Me
  profile_image: images/pf_blanco.jpg
  content: |
    I am a PhD Researcher at Ghent University with a background in 
    Engineering Physics and Physics and Astronomy. My research interests lie 
    in the realm of quantum mechanics, theoretical physics, and computational science.
    Outside of academics, I enjoy chess, padel, basketball, and triathlons.

# Education Section
education:
  title: Education
  layout: timeline
  content:
    - layout: left
      title: Ghent University
      caption: 2022 - 2024
      sub_title: M.Sc. in Physics and Astronomy
      description: |
        Grade: Summa Cum Laude
    - layout: left
      title: Ghent University
      caption: 2021 - 2023
      sub_title: M.Sc. in Engineering Physics
      description: |
        Grade: Summa Cum Laude
    - layout: left
      title: Ghent University
      caption: 2018 - 2021
      sub_title: B.Sc. in Engineering Physics
      description: |
        Grade: Magna Cum Laude

# Research and Publications
research:
  title: Research & Publications
  layout: list
  content:
    - title: "Quantum Dynamics in Reduced Dimensions"
      link: https://doi.org/example
      description: |
        A novel study of quantum systems in reduced dimensions.
    - title: "Computational Models for Quantum Behavior"
      link: https://doi.org/example2
      description: |
        Advanced computational techniques in theoretical quantum mechanics.

# Projects Section
projects:
  title: Projects
  layout: grid
  content:
    - title: "Quantum Dynamics Simulator"
      link: https://github.com/daanverraes/quantum-simulator
      description: |
        An open-source simulator for studying quantum mechanical systems.
      icon: fab fa-github
    - title: "Physics Visualization Toolkit"
      link: https://github.com/daanverraes/physics-viz
      description: |
        A toolkit for creating interactive physics visualizations.
      icon: fab fa-github

# Interests
interests:
  title: Interests
  layout: icons
  content:
    - title: Chess
      icon: fas fa-chess
    - title: Padel
      icon: fas fa-table-tennis
    - title: Basketball
      icon: fas fa-basketball-ball
    - title: Triathlon
      icon: fas fa-bicycle

# Skills
skills:
  title: Skills
  layout: bar
  content:
    - title: Python
      level: 95
    - title: Quantum Mechanics
      level: 90
    - title: Data Analysis
      level: 85
    - title: Machine Learning
      level: 80

# Contact Section
contact:
  title: Get in Touch
  email: daan.verraes@ugent.be
  phone: "+32 123 456 789"
  address: Ghent, Belgium
  social_links:
    - platform: LinkedIn
      username: daanverraes
    - platform: GitHub
      username: daanverraes
    - platform: Instagram
      username: daanverraes

# Footer
footer:
  show_references: true
  references_text: References available on request.
  copyright_text: "© 2024 Daan Verraes"
  additional_links:
    - text: Privacy Policy
      link: /privacy-policy
    - text: Terms of Use
      link: /terms-of-use
